version: 1
disable_existing_loggers: True

formatters:
    default:
        format: '%(asctime)s %(levelname)s [%(name)s:%(lineno)d] %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    file:
        class: logging.FileHandler
        level: NOTSET
        formatter: default
        filename: 'example.log'  # Output file path
        encoding: utf-8
        mode: w  # 'w' to overwrite each time, 'a' to append

    CLP_file:
        class: clp_logging.handlers.CLPFileHandler
        level: NOTSET
        fpath: 'example.clp.zst'

root:
    level: NOTSET
    handlers: [file, CLP_file]
