version: 1
disable_existing_loggers: True

formatters:
    default:
        format: '%(asctime)s %(levelname)s [%(name)s:%(lineno)d] %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    clp_file:
        class: clp_logging.handlers.CLPFileHandler
        level: INFO
        formatter: standard
        filename: 'D:\\test\\iCtrl\\example.clp.zst'

    clp_sock:
        class: clp_logging.handlers.CLPSockHandler
        level: INFO
        formatter: standard
        filename: 'D:\\test\\iCtrl\\example.clp.zst'
        mode: 'a'
        encoding: 'utf-8'
        create_listener: true

    loggers:
        "":
            level: INFO
            handlers: [clp_file, clp_sock ]
            propagate: no

root:
    level: DEBUG
    handlers: [clp_file]
